[[pages]]
path = "preprocessing.py"
name = "Preprocessing"
icon = "游눌"

[[pages]]
path = "wordcloud_fig.py"
name = "Word Cloud"
icon = "游눌"

[[pages]]
path = "tf-idf.py"
name = "TF IDF"
icon = "游눌"

[[pages]]
path = "tf-rf.py"
name = "TF RF"
icon = "游눌"
